USE SOX2016;
DROP TABLE dbo.DBA_SYS_PRIVS;
CREATE TABLE dbo.DBA_SYS_PRIVS (
DBNAME			VARCHAR(30)
,VERSION		VARCHAR(30)
,GRANTEE		VARCHAR(30)
,PRIVILEGE		VARCHAR(40)
,ADMIN_OPTION	VARCHAR(3)
,COMMON			VARCHAR(3)
)
