USE SOX2016;
DROP TABLE dbo.DBA_ROLE_PRIVS;
CREATE TABLE dbo.DBA_ROLE_PRIVS (
DBNAME				VARCHAR(30)
,VERSION				VARCHAR(30)
,GRANTEE			VARCHAR(30)
,GRANTED_ROLE		VARCHAR(30)
,ADMIN_OPTION		VARCHAR(3)
,DEFAULT_ROLE		VARCHAR(3)
,DELEGATE_OPTION	VARCHAR(3)
,COMMON				VARCHAR(3)
);