USE SOX2016;
DROP TABLE dbo.DBA_USERS;
CREATE TABLE dbo.DBA_USERS (
DBNAME							VARCHAR(30)
,VERSION						VARCHAR(30)
,USERNAME						VARCHAR(30)
,USER_ID						BIGINT
,PASSWORD						VARCHAR(30)
,ACCOUNT_STATUS					VARCHAR(32)
,LOCK_DATE						DATE
,EXPIRY_DATE					DATE
,DEFAULT_TABLESPACE				VARCHAR(30)
,TEMPORARY_TABLESPACE			VARCHAR(30)
,CREATED						DATE
,PROFILE						VARCHAR(30)
,INITIAL_RSRC_CONSUMER_GROUP	VARCHAR(30)
,EXTERNAL_NAME					VARCHAR(4000)
,PASSWORD_VERSIONS				VARCHAR(30)
,EDITIONS_ENABLED				VARCHAR(3)
,AUTHENTICATION_TYPE			VARCHAR(30)
,PROXY_ONLY_CONNECT				VARCHAR(3)
,COMMON							VARCHAR(3)
,LAST_LOGIN						DATE
,ORACLE_MAINTAINED				VARCHAR(3)
);
