DROP TABLE dbo.USER$;
CREATE TABLE dbo.USER$ (
DBNAME							VARCHAR(30)
,VERSION						VARCHAR(100)
,USER#							BIGINT
,NAME							VARCHAR(30)
,TYPE#							VARCHAR(30)
,PASSWORD						VARCHAR(max)
,DATATS#						VARCHAR(3)
,TEMPTS#						VARCHAR(3)
,CTIME							DATE
,PTIME							DATE
,EXPTIME						DATE
,LTIME							DATE
,RESOURCE$						VARCHAR(3)
,AUDIT$							VARCHAR(max)
,DEFROLE						VARCHAR(3)
,DEFGRP#						VARCHAR(30)
,DEFGRP_SEQ#					VARCHAR(30)
,ASTATUS						VARCHAR(3)
,LCOUNT							VARCHAR(3)
,DEFSCHCLASS					VARCHAR(30)
,EXT_USERNAME					VARCHAR(30)
,SPARE1							VARCHAR(max)
,SPARE2							VARCHAR(max)
,SPARE3							VARCHAR(max)
,SPARE4							VARCHAR(max)
,SPARE5							VARCHAR(max)
,SPARE6							VARCHAR(max)
,SPARE7							VARCHAR(max)
,SPARE8							VARCHAR(max)
,SPARE9							VARCHAR(max)
,SPARE10						VARCHAR(max)
,SPARE11						VARCHAR(max)
);
